# Introduction to NumPy

NumPy is a fundamental package for scientific computing in Python.
It allows you to work efficiently with multidimensional arrays (ndarray) and provides a wide variety of mathematical functions to operate on these arrays.

# Why use NumPy?

Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

# What is an “array”?

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

1, 5, 2, 0

A two-dimensional array would be like a table:

1, 5, 2, 0<br>
8, 3, 6, 1<br>
1, 7, 2, 9<br>

A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages. In NumPy, this idea is generalized to an arbitrary number of dimensions, and so the fundamental array class is called `ndarray`: it represents an “N-dimensional array”.

Most NumPy arrays have some restrictions. For instance:

    All elements of the array must be of the same type of data.

    Once created, the total size of the array can’t change.

    The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

For the remainder of this document, we will use the word “array” to refer to an instance of `ndarray`.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 25.3
[notice] To update, run: pip install --upgrade pip


# Array fundamentals

NumPy is a fundamental package for scientific computing in Python.
It allows you to work efficiently with multidimensional arrays (ndarray)
and provides a wide variety of mathematical functions to operate on these arrays.

### Importing NumPy
`
import numpy as np
`

In [2]:
# **Exercise 1**: Import the NumPy library using the alias `np`.
# (Write your code below)
import numpy as np

# Check:
assert 'np' in locals(), "NumPy has not been imported correctly with the alias 'np'."

## Creating Arrays

## Creating Arrays
A NumPy array is called an ndarray. You can create one from a Python list.

```
# Example:
array = np.array([1, 2, 3, 4])
print(array)
```

In [ ]:
# **Exercise 2**: Create a 1D NumPy array named array_1d containing the numbers 5, 6, 7, and 8.
# (Write your code below)
array_1d = np.array([5,6,7,8])

# Check:
assert array_1d[0] == 5, "The 1D array is incorrect."
assert array_1d[1] == 6, "The 1D array is incorrect."
assert array_1d[2] == 7, "The 1D array is incorrect."
assert array_1d[3] == 8, "The 1D array is incorrect."

## np.zeros
np.zeros creates an array filled with zeros.

```
# Example:
zeros_array = np.zeros((2, 3))
print(zeros_array)
```

In [ ]:
# **Exercise 1**: Create a 3x4 array named zeros_3x4 of zeros.
# (Write your code below)
zeros_3x4 = np.zeros((3,4))
print(zeros_3x4)

# Check:
assert zeros_3x4.shape == (3, 4) and np.all(zeros_3x4 == 0), "The zeros array is incorrect."

## np.ones
np.ones creates an array filled with ones.

```
# Example:
ones_array = np.ones((2, 3))
print(ones_array)
```

In [ ]:
# **Exercise 2**: Create a 5x2 array of ones named ones_5x2.
# (Write your code below)
ones_5x2 = np.ones((5,2))
print(ones_5x2)

# Check:
assert ones_5x2.shape == (5, 2) and np.all(ones_5x2 == 1), "The ones array is incorrect."

## np.empty
np.empty creates an array without initializing its entries.
The values are random and depend on the memory state.

```
# Example:
empty_array = np.empty((2, 3))
print(empty_array)
```

In [ ]:
# **Exercise 3**: Create a 4x3 array using np.empty named empty_4x3.
# (Write your code below)
empty_4x3 = np.empty((4,3))
print(empty_4x3)

# Check:
assert empty_4x3.shape == (4, 3), "The empty array shape is incorrect."

## np.arange
np.arange generates an array with a range of values, similar to Python's built-in range.

```
# Example:
range_array = np.arange(0, 10, 2)
print(range_array)
```

In [ ]:
# **Exercise 4**: Create an array named arange_array starting from 5, ending at 20 (exclusive), with a step size of 3.
# (Write your code below)
arange_array = np.arange(5,20,3)
print(arange_array)

# Check:
assert np.array_equal(arange_array, np.array([5, 8, 11, 14, 17])), "The np.arange array is incorrect."

## np.linspace
np.linspace generates an array of evenly spaced values between a specified start and end.

[np.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

```
# Example:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)
```

In [ ]:
# **Exercise 5**: Create an array named linspace_array of 6 evenly spaced values between 2 and 3 (inclusive).
# (Write your code below)
linspace_array = np.linspace(2,3,6)
print(linspace_array)

# Check:
assert np.allclose(linspace_array, np.array([2., 2.2, 2.4, 2.6, 2.8, 3.])), "The np.linspace array is incorrect."

## Array Attributes

## Array Attributes
NumPy arrays have attributes like shape, size, and ndim to get information about the array.

[numpy.ndarray.shape](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html)<br/>
[numpy.ndarray.size](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html)

```
# Example:
array = np.array([[1, 2], [3, 4]])
print("Shape:", array.shape)
print("Size:", array.size)
print("Number of dimensions:", array.ndim)
```

In [ ]:
# **Exercise 3**: Create a 2D array named array_2d of shape (3, 3) and check its shape, size, and dimensions.
# (Write your code below)
array_2d = np.zeros((3,3))

# Check:
assert array_2d.shape == (3, 3), "The shape is incorrect."
assert array_2d.size == 9, "The size is incorrect."
assert array_2d.ndim == 2, "The number of dimensions is incorrect."

## Array Operations


## Array Operations
You can perform element-wise operations like addition, multiplication, and more on NumPy arrays.

[numpy.add](https://numpy.org/doc/stable/reference/generated/numpy.add.html)<br/>
[numpy.prod](https://numpy.org/doc/stable/reference/generated/numpy.prod.html)

```
# Example:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Sum:", a + b)
print("Product:", a * b)
```

In [ ]:
# **Exercise 5**: Create two arrays of length 5, one filled with ones and the other with numbers from 1 to 5.
# Perform element-wise addition and multiplication.
# Name our array sum_array and array_prod
# (Write your code below)
array_a = np.array([1,1,1,1,1])
print(array_a)
array_b = np.arange(1,6,1)
print(array_b)

array_sum = np.add(array_a, array_b)
print(array_sum)
array_prod = array_a * array_b
print(array_prod)

# Check:
assert array_sum[0] == 2, "The sum is incorrect."
assert array_sum[1] == 3, "The sum is incorrect."
assert array_sum[2] == 4, "The sum is incorrect."
assert array_sum[3] == 5, "The sum is incorrect."
assert array_sum[4] == 6, "The sum is incorrect."
assert np.array_equal(array_prod, array_b), "The product is incorrect"

# Sorting and Concatenate

## np.sort
np.sort sorts the elements of an array in ascending order by default.
You can also sort along specific axes for multidimensional arrays.

[np.sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

```
# Example:
unsorted_array = np.array([3, 1, 2])
sorted_array = np.sort(unsorted_array)
print("Sorted array:", sorted_array)
```

In [ ]:
# **Exercise 1**: Create an array named sorted_array with the values [12, 5, 7, 3, 9] and sort it in ascending order.
# (Write your code below)
sorted_array = np.sort([12,5,7,3,9])

# Check:
assert np.array_equal(sorted_array, np.array([3, 5, 7, 9, 12])), "The sorted array is incorrect."


## Sorting along axes (Advanced)
You can sort a 2D array along a specific axis using np.sort.
Axis 0 sorts the columns, and axis 1 sorts the rows.

```
# Example:
array_2d = np.array([[3, 2, 1], [6, 5, 4]])
sorted_rows = np.sort(array_2d, axis=1)  # Sorts each row
print("Rows sorted:", sorted_rows)
```

In [ ]:
# **Exercise 2**: Create a 3x3 array and sort its rows and columns separately.
# (Write your code below)
array_3x3 = np.ones((3,3))
print("Original:\n", array_3x3)
array_3x3_sorted_rows = np.sort(array_3x3, axis=1)
print("Rows sorted:\n", array_3x3_sorted_rows)
array_3x3_sorted_cols = np.sort(array_3x3, axis=0)
print("Columns sorted:\n", array_3x3_sorted_cols)

## np.concatenate
np.concatenate is used to join two or more arrays along a specified axis.

```
# Example:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concatenated = np.concatenate((array_a, array_b))
print("Concatenated array:", concatenated)
```

In [ ]:
# **Exercise 3**: Concatenate two 1D arrays [10, 20, 30] and [40, 50, 60] (name the result concatenated_array).
# (Write your code below)
array_a = np.array([10,20,30])
array_b = np.array([40,50,60])
concatenated_array = np.concatenate((array_a, array_b))

# Check:
assert np.array_equal(concatenated_array, np.array([10, 20, 30, 40, 50, 60])), "The concatenated array is incorrect."


## Concatenating 2D arrays
You can concatenate along different axes in multidimensional arrays.
Axis 0 concatenates along rows, and axis 1 concatenates along columns.

```
# Example:
array_c = np.array([[1, 2], [3, 4]])
array_d = np.array([[5, 6], [7, 8]])
concat_axis_0 = np.concatenate((array_c, array_d), axis=0)  # Concatenate along rows
concat_axis_1 = np.concatenate((array_c, array_d), axis=1)  # Concatenate along columns
print("Concatenated along axis 0:\n", concat_axis_0)
print("Concatenated along axis 1:\n", concat_axis_1)
```

In [ ]:
# **Exercise 4**: Create two 2D arrays of shape (2, 3) and concatenate them:
# - Along axis 0 (along rows)
# - Along axis 1 (along columns)

# (Write your code below)
array_a = np.ones((2,3))
array_b = np.zeros((2,3))
concat_axis_0 = np.concatenate((array_a, array_b), axis=0)
concat_axis_1 = np.concatenate((array_a, array_b), axis=1)
print("Concatenated along axis 0:\n", concat_axis_0)
print("Concatenated along axis 1:\n", concat_axis_1)

## np.hstack
np.hstack is used to horizontally stack arrays (along the second axis).
It concatenates arrays along the columns.

```
# Example:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
hstacked = np.hstack((array_a, array_b))
print("Horizontally stacked array:", hstacked)
```

In [ ]:
# **Exercise 1**: Create two 1D arrays [10, 20, 30] and [40, 50, 60], and horizontally stack them using np.hstack.
# name the output hstacked_array
# (Write your code below)
array_a = np.array([10,20,30])
array_b = np.array([40,50,60])
hstacked_array = np.hstack((array_a, array_b))
print(hstacked_array)

# Check:
assert np.array_equal(hstacked_array, np.array([10, 20, 30, 40, 50, 60])), "The horizontally stacked array is incorrect."


## np.vstack
np.vstack is used to vertically stack arrays (along the first axis).
It concatenates arrays along the rows.

```
# Example:
array_c = np.array([[1, 2], [3, 4]])
array_d = np.array([[5, 6], [7, 8]])
vstacked = np.vstack((array_c, array_d))
print("Vertically stacked array:\n", vstacked)
```

In [ ]:
# **Exercise 2**: Create two 2D arrays of shape (2, 2) with values [[10, 20], [30, 40]] and [[50, 60], [70, 80]].
# Vertically stack them using np.vstack and name the output hstacked_array.
# (Write your code below)
array_a = np.array([[10,20], [30,40]])
array_b = np.array([[50,60], [70,80]])
vstacked_array = np.vstack((array_a, array_b))

# Check:
assert vstacked_array.shape == (4, 2), "The vertically stacked array shape is incorrect."
assert np.array_equal(vstacked_array, np.array([[10, 20], [30, 40], [50, 60], [70, 80]])), "The vertically stacked array is incorrect."


## Stacking 1D arrays into 2D arrays
You can use np.vstack or np.hstack to stack 1D arrays into 2D arrays.

```
# Example:
array_e = np.array([1, 2, 3])
array_f = np.array([4, 5, 6])
vstacked_1d = np.vstack((array_e, array_f))
print("1D arrays stacked vertically into 2D:\n", vstacked_1d)
```

In [4]:
# **Exercise 3**: Create two 1D arrays [7, 8, 9] and [10, 11, 12], and stack them vertically into a 2x3 array using np.vstack.
# Name the output vstacked_1d_arrays.
# (Write your code below)
array_a = np.array([7,8,9])
array_b = np.array([10,11,12])
vstacked_1d_arrays = np.vstack((array_a, array_b))
print(vstacked_1d_arrays)

# Check:
assert np.array_equal(vstacked_1d_arrays, np.array([[7, 8, 9], [10, 11, 12]])), "The stacked 2x3 array is incorrect."


[[ 7  8  9]
 [10 11 12]]


## Combining hstack and vstack
You can use both functions together to stack arrays in different directions.

```
# Example:
array_g = np.array([1, 2, 3])
array_h = np.array([4, 5, 6])
hstacked = np.hstack((array_g, array_h))  # Horizontal stacking
vstacked = np.vstack((hstacked, hstacked))  # Vertical stacking of the result
print("Combined stacking:\n", vstacked)
```

In [5]:
# **Exercise 4**: Horizontally stack two 1D arrays [100, 200, 300] and [400, 500, 600],
# then vertically stack the result with itself. Name the output combined_stack.
# (Write your code below)
array_a = np.array([100,200,300])
array_b = np.array([400,500,600])
hstacked = np.hstack((array_a, array_b))
combined_stack = np.vstack((hstacked, hstacked))

# Check:
assert combined_stack.shape == (2, 6), "The final stacked array shape is incorrect."
assert np.array_equal(combined_stack, np.array([[100, 200, 300, 400, 500, 600], [100, 200, 300, 400, 500, 600]])), "The combined stacking is incorrect."

# Reshaping

## np.reshape
np.reshape allows you to change the shape of an array without changing its data.

```
# Example:
array = np.arange(6)  # Create a 1D array of values [0, 1, 2, 3, 4, 5]
reshaped = np.reshape(array, (2, 3))  # Reshape into a 2x3 array
print(reshaped)
```

In [9]:
# **Exercise 1**: Create a 1D array with values from 0 to 11 and reshape it into a 3x4 array. name the output reshaped_array.
# (Write your code below)
array = np.arange(0,12,1)
print(array)
reshaped_array = np.reshape(array,(3,4))
print(reshaped_array)

# Check:
assert reshaped_array.shape == (3, 4), "The reshaped array shape is incorrect."
assert np.array_equal(reshaped_array, np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])), "The reshaped array values are incorrect."


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## arr.reshape()
The reshape method can also be called directly from the array object.

```
# Example:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped = array.reshape((3, 2))  # Reshape into a 3x2 array
print(reshaped)
```

In [11]:
# **Exercise 2**: Create a 1D array of 8 elements and reshape it into a 2x4 array. Name the output arr_reshaped.
# (Write your code below)
array = np.arange(0,8,1)
arr_reshaped = array.reshape((2,4))

# Check:
assert arr_reshaped.shape == (2, 4), "The reshaped array shape is incorrect."

## np.newaxis
np.newaxis is used to increase the dimensions of an array by one dimension.
It is useful for adding new axes to an array.

```
# Example:
array_1d = np.array([1, 2, 3])
array_2d = array_1d[:, np.newaxis]  # Convert 1D array to 2D (column vector)
print(array_2d)
```

In [14]:
# **Exercise 3**: Create a 1D array of 5 elements and use np.newaxis to transform it into a column vector (5x1).
# Name the output array_column.
# (Write your code below)
array = np.arange(0,5)
array_column = array[:, np.newaxis]
print(array_column)

# Check:
assert array_column.shape == (5, 1), "The newaxis operation is incorrect."

[[0]
 [1]
 [2]
 [3]
 [4]]


## np.expand_dims
np.expand_dims is similar to np.newaxis but allows you to specify where to add the new axis.

```
# Example:
array = np.array([1, 2, 3])
expanded_array = np.expand_dims(array, axis=0)  # Add a new axis at position 0 (convert to row vector)
print(expanded_array)
```

In [15]:
# **Exercise 4**: Create a 1D array of 6 elements and use np.expand_dims to add a new axis at position 1.
# Name the output expanded_array.
# (Write your code below)
array = np.arange(0,6)
expanded_array = np.expand_dims(array, axis=1)

# Check:
assert expanded_array.shape == (6, 1), "The expanded array shape is incorrect."

# Advanced Exercise (Bonus)
Combine reshaping, newaxis, and expand_dims for multidimensional manipulations.

In [25]:
# **Exercise 5**: Create a 2D array of shape (3, 3).
# - Reshape it into a 1D array and name it reshaped_1d.
# - Add a new axis using np.newaxis to convert it into a row vector (1x9) and name it row_vector.
# - Use np.expand_dims to transform it into a column vector (9x1) and name it column_vector.
# (Write your code below)
array = np.ones((3,3))
reshaped_1d = np.reshape(array,(9))
row_vector = reshaped_1d[np.newaxis, :]
column_vector = np.expand_dims(reshaped_1d, axis=1)

# Check:
assert reshaped_1d.shape == (9,), "The reshape to 1D is incorrect."
assert row_vector.shape == (1, 9), "The row vector transformation is incorrect."
assert column_vector.shape == (9, 1), "The column vector transformation is incorrect."